---
- name: Setup the machine as a root user
  hosts: localhost
  become: yes 
  become_user: root
  roles:
    - { role: flyinggecko.i3, tags: windowmanager,
        i3_state: "present",
        i3_user: [
          { name: pierre, i3config: [ i3.base ], i3status: i3status.desktop }
        ] }
    - { role: franklinkim.vim, tags: vim,
        vim_config: [ 'set expandtab' ] }
    - { role: jdauphant.sublimetext, tags: sublimetext }
    - { role: igor_mukhin.sublimetext3_packagecontrol, tags: sublimetext,
        packagecontrol_packages: [
          "AutoFileName",
          "Git",
          "GitGutter",
          "Terminal" ] }
    - { role: geerlingguy.git, tags: git,
        git_packages: [
          "git-gui",
          "gitk" ] }
    - { role: kosssi.phpstorm, tags: phpstorm }
    - { role: ansiblebit.oracle-java, tags: phpstorm,
        oracle_java_set_as_default: yes }
    - { role: franklinkim.docker, tags: docker }
    - { role: franklinkim.docker-compose, tags: docker,
        docker_compose_version: 1.4.1 }
    - { role: glennr.oh-my-zsh, tags: shell,
        user: pierre }
    - { role: devbox.chrome, tags: browser }
  tasks:
    - name: Window manager related packages are installed
      apt: name={{ item }} state=present
      tags: windowmanager
      with_items:
       - gnome-settings-daemon
       - suckless-tools

- name: Setup user settings
  hosts: localhost
  become: no
  tasks:
    - name: ensure Git is properly configured
      template: src=templates/gitconfig.j2 dest={{ansible_env.HOME}}/.gitconfig

# TODO
# Docker: extend to have nginx proxy:
#   see https://github.com/weareinteractive/ansible-docker/blob/master/defaults/main.yml
# https://github.com/clvv/fasd
# Vault for passwords and sensitive data: http://docs.ansible.com/ansible/playbooks_vault.html
#
# Galaxy
#   apt-repository: https://galaxy.ansible.com/list#/roles/3632
#   php: https://galaxy.ansible.com/list#/roles/1232
#
# BIOS :
#   switch ctrl / fn