---
- name: Setup the machine as a root user
  hosts: localhost
  become: yes 
  become_user: root
  roles:
    - { role: flyinggecko.i3, tags: windowmanager,
        i3_state: "present",
        i3_user: [
          { name: pierre, i3config: [ i3.base ], i3status: i3status.desktop }
        ] }
    - { role: franklinkim.vim, tags: vim,
        vim_config: [ 'set expandtab' ] }
    - { role: jdauphant.sublimetext, tags: sublimetext }
    - { role: igor_mukhin.sublimetext3_packagecontrol, tags: sublimetext,
        packagecontrol_packages: [
          "AutoFileName",
          "Git",
          "GitGutter",
          "Side​Bar​Enhancements",
          "Terminal" ] }
    - { role: geerlingguy.git, tags: git,
        git_packages: [
          "git-gui",
          "gitk",
          "git-flow" ] }
    - { role: kosssi.phpstorm, tags: phpstorm }
    - { role: ansiblebit.oracle-java, tags: phpstorm,
        oracle_java_set_as_default: yes }
    - { role: franklinkim.docker, tags: docker,
        docker_containers: [
          {
            image: jwilder/nginx-proxy,
            name: nginx-proxy,
            ports: ["80:80"],
            volumes: [
              "/var/run/docker.sock:/tmp/docker.sock:ro",
              "/home/pierre/dotfiles/my_nginx_proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro"
            ]
          }
        ]
      }
    - { role: franklinkim.docker-compose, tags: docker,
        docker_compose_version: 1.4.1 }
    - { role: glennr.oh-my-zsh, tags: shell,
        user: pierre }
    - { role: devbox.chrome, tags: browser }
    - { role: nickjj.dnsmasq, tags: dnsmasq,
        dnsmasq_tld: test }
  tasks:
    - name: Window manager related packages are installed
      apt: name={{ item }} state=present
      tags: windowmanager
      with_items:
       - gnome-settings-daemon
       - suckless-tools
       - pcmanfm
       - dunst
    - name: Other convenient tools are installed
      apt: name={{ item }} state=present
      tags: tools
      with_items:
       - ack-grep
       - filezilla
       - gimp
       - htop
       - meld
       - pandoc
       - shutter
       - exfat-utils
       - exfat-fuse

- name: Setup user settings
  hosts: localhost
  become: no
  tasks:
    - name: ensure Git is properly configured
      template: src=templates/gitconfig.j2 dest={{ansible_env.HOME}}/.gitconfig

# TODO
# i3 bugfixes:
#   http://blog.hugochinchilla.net/2013/03/using-gnome-3-with-i3-window-manager/ - usr/share/xsessions/gnome-i3.desktop
#   ++ http://www.draconianoverlord.com/2014/05/26/from-xmonad-to-i3.html
#   Virer iBus (cf http://doc.ubuntu-fr.org/ibus)
#
# https://github.com/sgentle/caniuse-cmd
#
# sudo usermod -aG docker pierre ?
# https://github.com/clvv/fasd
# Dropbox
# Vault for passwords and sensitive data: http://docs.ansible.com/ansible/playbooks_vault.html
#
# SSh-agent
# Galaxy
#   apt-repository: https://galaxy.ansible.com/list#/roles/3632
#   php: https://galaxy.ansible.com/list#/roles/1232
#
# Refactoring:
#   Nginx-proxy: move the config file by copying it where it belongs