# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
      ./configuration-override.home-laptop.nix
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/3f2c0260-be76-4fbf-9291-4d8778d36757";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/1d2acd42-9341-41de-9725-b3b5ece30720"; }
    ];

  nix.settings.max-jobs = lib.mkDefault 4;

  # Conflicts with tlp
  # powerManagement.cpuFreqGovernor = "powersave";

  hardware.pulseaudio.enable = true;
}
